### ISSUE TITLE
Tokyo is broken in Safari 6.0.3

### ISSUE THREAD

**Issue by mathias-erik** [Edicy/design-tokyo#1]
http://forum.edicy.com/forums/design-and-content/topics/search-pop-up#post_1524

Tokyo: menu issues: http://i.imgur.com/H5Jjwv5.png
Tokyo only looks good in very small browser window, probably because it thinks it’s a mobile browser? http://i.imgur.com/m6n3vAs.png

**Comment by kaspar-naaber** [comment]
The image links are broken and Safari 6.0.3 is more than 2 years old version. Tokyo is also a legacy template so I guess we can close this issue without fixing.
